---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx
  namespace: cluster-config
spec:
  chart:
    spec:
      chart: nginx
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: nginx
  install:
    timeout: 20m
    createNamespace: true
    remediation:
      retries: 3
  interval: 1m0s
  releaseName: nginx
  targetNamespace: nginx
